name: Dump Entities from Baserow

on:
  # schedule:
  # - cron: "13 */12 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
      BASEROW_USER: ${{secrets.BASEROW_USER}}
      BASEROW_PW: ${{secrets.BASEROW_PW}}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: dump the data
        run: |
          python dump_data.py
      - name: denormalize dump
        run: |
          python denormalize.py
      - name: data dump to xml
        run: |
          python json2xml.py
      - name: add relations to xml
        run: |
          python add_relations.py
      - name: create pmb beacon
        run: |
          python pmb-beacon-generator.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Downloaded/Updated Data
